# Generated by Django 3.2.16 on 2023-01-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
