# Generated by Django 3.2.16 on 2023-01-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
