# Generated by Django 3.2.16 on 2023-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_userprofile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spravochnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField(default=0, verbose_name='Balance')),
            ],
        ),
    ]
