# Generated by Django 3.2.16 on 2023-02-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_auto_20230205_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spravochnik',
        ),
    ]
