# Generated by Django 3.2.16 on 2023-02-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_delete_spravochnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(default=1, max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
