# Generated by Django 3.2.16 on 2023-01-22 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.AlterModelTable(
            name='good',
            table='Good',
        ),
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='Shop',
        ),
        migrations.AlterModelTable(
            name='shoppingcart',
            table='ShoppingCart',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_goods.category'),
        ),
    ]
