# Generated by Django 3.2.16 on 2023-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_auto_20230122_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, upload_to='images/icons', verbose_name='иконки категорий'),
        ),
    ]
