# Generated by Django 3.2.16 on 2023-02-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_userprofile_avatar'),
        ('app_goods', '0011_auto_20230205_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.userprofile'),
        ),
    ]
