# Generated by Django 3.2.16 on 2023-03-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0015_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=36, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('1', 'Обычная доставка'), ('2', 'Экспресс доставка')], default=1, max_length=2, verbose_name='Тип доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'Онлайн картой'), ('2', 'Онлайн со случайного чужого счета')], default=1, max_length=2, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='check_summ',
            field=models.DecimalField(decimal_places=2, max_digits=400, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='ShoppingCardItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=400, verbose_name='сумма')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.order')),
            ],
            options={
                'db_table': 'ShoppingCartLog',
            },
        ),
    ]
