# Generated by Django 3.2.16 on 2023-03-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0017_auto_20230311_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_number',
            field=models.IntegerField(null=True, verbose_name='номер счёта'),
        ),
    ]
