# Generated by Django 3.2.16 on 2023-04-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0019_auto_20230326_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_free_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
